# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/edge/clion-2019.2.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/edge/clion-2019.2.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/edge/RayTracing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/edge/RayTracing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/edge/clion-2019.2.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/edge/clion-2019.2.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edge/RayTracing/CMakeFiles /home/edge/RayTracing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edge/RayTracing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ray_tracing

# Build rule for target.
ray_tracing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ray_tracing
.PHONY : ray_tracing

# fast build rule for target.
ray_tracing/fast:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/build
.PHONY : ray_tracing/fast

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

Dielectric.o: Dielectric.cpp.o

.PHONY : Dielectric.o

# target to build an object file
Dielectric.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Dielectric.cpp.o
.PHONY : Dielectric.cpp.o

Dielectric.i: Dielectric.cpp.i

.PHONY : Dielectric.i

# target to preprocess a source file
Dielectric.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Dielectric.cpp.i
.PHONY : Dielectric.cpp.i

Dielectric.s: Dielectric.cpp.s

.PHONY : Dielectric.s

# target to generate assembly for a file
Dielectric.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Dielectric.cpp.s
.PHONY : Dielectric.cpp.s

HitableList.o: HitableList.cpp.o

.PHONY : HitableList.o

# target to build an object file
HitableList.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/HitableList.cpp.o
.PHONY : HitableList.cpp.o

HitableList.i: HitableList.cpp.i

.PHONY : HitableList.i

# target to preprocess a source file
HitableList.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/HitableList.cpp.i
.PHONY : HitableList.cpp.i

HitableList.s: HitableList.cpp.s

.PHONY : HitableList.s

# target to generate assembly for a file
HitableList.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/HitableList.cpp.s
.PHONY : HitableList.cpp.s

Lambertian.o: Lambertian.cpp.o

.PHONY : Lambertian.o

# target to build an object file
Lambertian.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Lambertian.cpp.o
.PHONY : Lambertian.cpp.o

Lambertian.i: Lambertian.cpp.i

.PHONY : Lambertian.i

# target to preprocess a source file
Lambertian.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Lambertian.cpp.i
.PHONY : Lambertian.cpp.i

Lambertian.s: Lambertian.cpp.s

.PHONY : Lambertian.s

# target to generate assembly for a file
Lambertian.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Lambertian.cpp.s
.PHONY : Lambertian.cpp.s

Metal.o: Metal.cpp.o

.PHONY : Metal.o

# target to build an object file
Metal.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Metal.cpp.o
.PHONY : Metal.cpp.o

Metal.i: Metal.cpp.i

.PHONY : Metal.i

# target to preprocess a source file
Metal.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Metal.cpp.i
.PHONY : Metal.cpp.i

Metal.s: Metal.cpp.s

.PHONY : Metal.s

# target to generate assembly for a file
Metal.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Metal.cpp.s
.PHONY : Metal.cpp.s

Ray.o: Ray.cpp.o

.PHONY : Ray.o

# target to build an object file
Ray.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Ray.cpp.o
.PHONY : Ray.cpp.o

Ray.i: Ray.cpp.i

.PHONY : Ray.i

# target to preprocess a source file
Ray.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Ray.cpp.i
.PHONY : Ray.cpp.i

Ray.s: Ray.cpp.s

.PHONY : Ray.s

# target to generate assembly for a file
Ray.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Ray.cpp.s
.PHONY : Ray.cpp.s

Sphere.o: Sphere.cpp.o

.PHONY : Sphere.o

# target to build an object file
Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Sphere.cpp.o
.PHONY : Sphere.cpp.o

Sphere.i: Sphere.cpp.i

.PHONY : Sphere.i

# target to preprocess a source file
Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Sphere.cpp.i
.PHONY : Sphere.cpp.i

Sphere.s: Sphere.cpp.s

.PHONY : Sphere.s

# target to generate assembly for a file
Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Sphere.cpp.s
.PHONY : Sphere.cpp.s

Utility.o: Utility.cpp.o

.PHONY : Utility.o

# target to build an object file
Utility.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Utility.cpp.o
.PHONY : Utility.cpp.o

Utility.i: Utility.cpp.i

.PHONY : Utility.i

# target to preprocess a source file
Utility.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Utility.cpp.i
.PHONY : Utility.cpp.i

Utility.s: Utility.cpp.s

.PHONY : Utility.s

# target to generate assembly for a file
Utility.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Utility.cpp.s
.PHONY : Utility.cpp.s

Vector.o: Vector.cpp.o

.PHONY : Vector.o

# target to build an object file
Vector.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Vector.cpp.o
.PHONY : Vector.cpp.o

Vector.i: Vector.cpp.i

.PHONY : Vector.i

# target to preprocess a source file
Vector.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Vector.cpp.i
.PHONY : Vector.cpp.i

Vector.s: Vector.cpp.s

.PHONY : Vector.s

# target to generate assembly for a file
Vector.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/Vector.cpp.s
.PHONY : Vector.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracing.dir/build.make CMakeFiles/ray_tracing.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ray_tracing"
	@echo "... edit_cache"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... Dielectric.o"
	@echo "... Dielectric.i"
	@echo "... Dielectric.s"
	@echo "... HitableList.o"
	@echo "... HitableList.i"
	@echo "... HitableList.s"
	@echo "... Lambertian.o"
	@echo "... Lambertian.i"
	@echo "... Lambertian.s"
	@echo "... Metal.o"
	@echo "... Metal.i"
	@echo "... Metal.s"
	@echo "... Ray.o"
	@echo "... Ray.i"
	@echo "... Ray.s"
	@echo "... Sphere.o"
	@echo "... Sphere.i"
	@echo "... Sphere.s"
	@echo "... Utility.o"
	@echo "... Utility.i"
	@echo "... Utility.s"
	@echo "... Vector.o"
	@echo "... Vector.i"
	@echo "... Vector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

